### PR TITLE
'break' signal to break a running walk

### PR DESCRIPTION
**Pull request by pste**
The on('break') allows to programmatically stop a running walk

### CODE REVIEW

**Comment by CodeIter** [comment]
good feature really, but It is not necessary to change git URL

**Comment by daaku** [comment]
I get what your goal is here, in that you want to abort/break the walk somehow while it's running. This isn't bulletproof way to do it though, since async `lstat` calls in the `go` function may still emit events. Additionally doing this by firing a `break` event on the `Walker` is a strange way to do it, would be better to have a function on the class to do it. I'll think about how to go about adding this feature though to be honest I'm considering letting the caller handle it somehow.

**Comment by pste** [comment]
The main scope of having a 'break' event is to interrupt a -slow- disk scan because of a successful event. Imagine to implement a file seeker: when found I need to stop the walker and go on with my code.

I agree this PR is not the best way to handle the problem; it's code from 4 years ago....today I'll do it in another way -i.e. setting the '_pending' to 0 to **really** stop the walk-

Said so I'm closing the request

**Comment by tracycollins** [comment]
Sorry to resurrect this, but how would you suggest that the caller cleanly abort a walk in progress?

**Comment by daaku** [comment]
The asynchronous nature of how this library works means there isn't a simple loop to "break" from. One way to do this is:

```javascript
var done = false;
Walker('/etc/')
  .on('entry', function(entry, stat) {
    if (done) {
      return;
    }

    if (entry === 'what-i-want') {
      done = true;
    }

    //...
  })
```

There are ways to change this library to do what you want, but I'm not looking to add any new features here.

**Comment by tracycollins** [comment]
> The asynchronous nature of how this library works means there isn't a simple loop to "break" from. One way to do this is:
> 
> ```js
> var done = false;
> Walker('/etc/')
>   .on('entry', function(entry, stat) {
>     if (done) {
>       return;
>     }
> 
>     if (entry === 'what-i-want') {
>       done = true;
>     }
> 
>     //...
>   })
> ```
> 
> There are ways to change this library to do what you want, but I'm not looking to add any new features here.

Thanks for the tip. I'll try this method.

**Pull request closed without merging**
